theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://github.com/SWCTaipei/SWCWeb/archive/master.zip
  tar_url: another value

title: [The title of your site]
description: [A short description of your site's purpose]
